-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";
-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';
-- Create "organisations" table
CREATE TABLE "public"."organisations" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create "goose_db_version" table
CREATE TABLE "public"."goose_db_version" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "version_id" bigint NOT NULL,
  "is_applied" boolean NOT NULL,
  "tstamp" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create "applications" table
CREATE TABLE "public"."applications" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "name" text NOT NULL,
  "description" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "applications_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_applications_name_org" to table: "applications"
CREATE UNIQUE INDEX "idx_applications_name_org" ON "public"."applications" ("org_id", "name");
-- Create index "idx_applications_org" to table: "applications"
CREATE INDEX "idx_applications_org" ON "public"."applications" ("org_id");
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "sub" text NULL,
  "email" public.citext NOT NULL,
  "name" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "users_org_id_email_key" UNIQUE ("org_id", "email"),
  CONSTRAINT "users_sub_key" UNIQUE ("sub"),
  CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_users_org_email" to table: "users"
CREATE INDEX "idx_users_org_email" ON "public"."users" ("org_id", "email");
-- Create index "idx_users_sub" to table: "users"
CREATE INDEX "idx_users_sub" ON "public"."users" ("sub");
-- Create "api_keys" table
CREATE TABLE "public"."api_keys" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "app_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "key_prefix" text NOT NULL,
  "secret_phc" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "last_four" text NOT NULL,
  "expires_at" timestamptz NULL,
  "last_used_at" timestamptz NULL,
  "metadata" jsonb NOT NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "api_keys_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "public"."applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "api_keys_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "api_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_api_keys_org_app" to table: "api_keys"
CREATE INDEX "idx_api_keys_org_app" ON "public"."api_keys" ("org_id", "app_id");
-- Create index "idx_api_keys_prefix" to table: "api_keys"
CREATE INDEX "idx_api_keys_prefix" ON "public"."api_keys" ("key_prefix");
-- Create "application_configs" table
CREATE TABLE "public"."application_configs" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "app_id" uuid NOT NULL,
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "environment" text NOT NULL,
  "config" jsonb NOT NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "application_configs_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "public"."applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "application_configs_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_app_configs_app_env" to table: "application_configs"
CREATE UNIQUE INDEX "idx_app_configs_app_env" ON "public"."application_configs" ("app_id", "environment");
-- Create index "idx_app_configs_org" to table: "application_configs"
CREATE INDEX "idx_app_configs_org" ON "public"."application_configs" ("org_id");
-- Create "models" table
CREATE TABLE "public"."models" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "provider" text NOT NULL,
  "model_name" text NOT NULL,
  "deployment_name" text NULL,
  "endpoint_url" text NOT NULL,
  "auth_type" text NOT NULL,
  "auth_config" jsonb NOT NULL DEFAULT '{}',
  "metadata" jsonb NOT NULL DEFAULT '{}',
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "models_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_models_org_enabled" to table: "models"
CREATE INDEX "idx_models_org_enabled" ON "public"."models" ("org_id", "enabled");
-- Create index "idx_models_provider_model" to table: "models"
CREATE INDEX "idx_models_provider_model" ON "public"."models" ("org_id", "provider", "model_name");
-- Create "roles" table
CREATE TABLE "public"."roles" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "name" text NOT NULL,
  "description" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "roles_name_key" UNIQUE ("name")
);
-- Create "organisation_invites" table
CREATE TABLE "public"."organisation_invites" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "email" public.citext NOT NULL,
  "role_id" uuid NULL,
  "invited_by" uuid NOT NULL,
  "token" text NOT NULL,
  "accepted" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "organisation_invites_token_key" UNIQUE ("token"),
  CONSTRAINT "organisation_invites_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "organisation_invites_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "organisation_invites_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "uniq_pending_invite_per_email_per_org" to table: "organisation_invites"
CREATE UNIQUE INDEX "uniq_pending_invite_per_email_per_org" ON "public"."organisation_invites" ("org_id", "email") WHERE (accepted = false);
-- Create "organisation_keys" table
CREATE TABLE "public"."organisation_keys" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "key_hash" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "last_used" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "organisation_keys_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_org_keys_org" to table: "organisation_keys"
CREATE INDEX "idx_org_keys_org" ON "public"."organisation_keys" ("org_id");
-- Create "organisation_roles" table
CREATE TABLE "public"."organisation_roles" (
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "role_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("org_id", "role_id"),
  CONSTRAINT "organisation_roles_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "organisation_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "organisation_users" table
CREATE TABLE "public"."organisation_users" (
  "user_id" uuid NOT NULL,
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "org_id"),
  CONSTRAINT "organisation_users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "organisation_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_org_users_org" to table: "organisation_users"
CREATE INDEX "idx_org_users_org" ON "public"."organisation_users" ("org_id");
-- Create index "idx_org_users_user" to table: "organisation_users"
CREATE INDEX "idx_org_users_user" ON "public"."organisation_users" ("user_id");
-- Create "policies" table
CREATE TABLE "public"."policies" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "policy_type" text NOT NULL,
  "config" jsonb NOT NULL DEFAULT '{}',
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "policies_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_policies_org" to table: "policies"
CREATE INDEX "idx_policies_org" ON "public"."policies" ("org_id");
-- Create index "idx_policies_type" to table: "policies"
CREATE INDEX "idx_policies_type" ON "public"."policies" ("policy_type");
-- Create "policy_applications" table
CREATE TABLE "public"."policy_applications" (
  "policy_id" uuid NOT NULL,
  "app_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("policy_id", "app_id"),
  CONSTRAINT "policy_applications_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "public"."applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "policy_applications_policy_id_fkey" FOREIGN KEY ("policy_id") REFERENCES "public"."policies" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_policy_applications_app" to table: "policy_applications"
CREATE INDEX "idx_policy_applications_app" ON "public"."policy_applications" ("app_id");
-- Create index "idx_policy_applications_policy" to table: "policy_applications"
CREATE INDEX "idx_policy_applications_policy" ON "public"."policy_applications" ("policy_id");
-- Create "usage_metrics" table
CREATE TABLE "public"."usage_metrics" (
  "id" uuid NOT NULL DEFAULT public.uuid_generate_v4(),
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "app_id" uuid NOT NULL,
  "api_key_id" uuid NOT NULL,
  "model_id" uuid NULL,
  "provider" text NOT NULL,
  "model_name" text NOT NULL,
  "prompt_tokens" integer NOT NULL DEFAULT 0,
  "completion_tokens" integer NOT NULL DEFAULT 0,
  "total_tokens" integer NOT NULL DEFAULT 0,
  "request_size_bytes" integer NOT NULL DEFAULT 0,
  "response_size_bytes" integer NOT NULL DEFAULT 0,
  "timestamp" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "usage_metrics_api_key_id_fkey" FOREIGN KEY ("api_key_id") REFERENCES "public"."api_keys" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "usage_metrics_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "public"."applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "usage_metrics_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "public"."models" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "usage_metrics_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_usage_metrics_app_timestamp" to table: "usage_metrics"
CREATE INDEX "idx_usage_metrics_app_timestamp" ON "public"."usage_metrics" ("app_id", "timestamp");
-- Create index "idx_usage_metrics_org_timestamp" to table: "usage_metrics"
CREATE INDEX "idx_usage_metrics_org_timestamp" ON "public"."usage_metrics" ("org_id", "timestamp");
-- Create index "idx_usage_metrics_timestamp" to table: "usage_metrics"
CREATE INDEX "idx_usage_metrics_timestamp" ON "public"."usage_metrics" ("timestamp");
-- Create "user_roles" table
CREATE TABLE "public"."user_roles" (
  "user_id" uuid NOT NULL,
  "role_id" uuid NOT NULL,
  "org_id" uuid NOT NULL DEFAULT public.app_current_org(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "role_id", "org_id"),
  CONSTRAINT "user_roles_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_user_roles_org_role" to table: "user_roles"
CREATE INDEX "idx_user_roles_org_role" ON "public"."user_roles" ("org_id", "role_id");
-- Create index "idx_user_roles_org_user" to table: "user_roles"
CREATE INDEX "idx_user_roles_org_user" ON "public"."user_roles" ("org_id", "user_id");
