// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	UserID    uuid.UUID          `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastUsed  pgtype.Timestamptz `json:"last_used"`
}

type Organisation struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganisationInvite struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Email     string             `json:"email"`
	RoleID    *uuid.UUID         `json:"role_id"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Token     string             `json:"token"`
	Accepted  bool               `json:"accepted"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type OrganisationKey struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastUsed  pgtype.Timestamptz `json:"last_used"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Sub       *string            `json:"sub"`
	Email     string             `json:"email"`
	Name      *string            `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID          `json:"user_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	OrgID     uuid.UUID          `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
