// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: org_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const ensureOrgMembership = `-- name: EnsureOrgMembership :exec
INSERT INTO organisation_users (org_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type EnsureOrgMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) EnsureOrgMembership(ctx context.Context, arg EnsureOrgMembershipParams) error {
	_, err := q.db.Exec(ctx, ensureOrgMembership, arg.OrgID, arg.UserID)
	return err
}
