// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleToOrg = `-- name: AssignRoleToOrg :exec
INSERT INTO organisation_roles (org_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING org_id, role_id, created_at
`

type AssignRoleToOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToOrg(ctx context.Context, arg AssignRoleToOrgParams) error {
	_, err := q.db.Exec(ctx, assignRoleToOrg, arg.OrgID, arg.RoleID)
	return err
}
