// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateOrg(ctx context.Context, name string) (Organisation, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindOrgByID(ctx context.Context, id uuid.UUID) (Organisation, error)
	FindRoleByOrgAndName(ctx context.Context, arg FindRoleByOrgAndNameParams) (Role, error)
	FindUserBySubOrEmail(ctx context.Context, arg FindUserBySubOrEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
